on:
  push:
    branches: [ "main" , "stages" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' 
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with: 
          version: latest

      - name: Build
        run: go build -v ./...

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Show coverage
        run: go tool cover -func=coverage.out

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
  htmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Golangci-lint
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: HTML Golangci-lint
        run: |
          go get github.com/go-playground/validator/v10
          go-html-validator ./templates
    
